version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    container_name: db-postgres
    command:
      "postgres -c 'max_connections=500'"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - "5432:5432"

  backend:
    container_name: backend-rails
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "./bin/rails server"
    depends_on:
      - 'db'
    environment:
        RAILS_ENV: ${RAILS_ENV}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASS: ${POSTGRES_PASS}
        POSTGRES_HOST: ${POSTGRES_HOST}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
        JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000

  frontend:
    container_name: frontend-react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - 'backend'
    environment:
      RAILS_ENV: ${BACKEND_HOST}
    ports:
      - 80:80